name: facebookclone
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  flat_icons_flutter: ^1.0.2
  image_picker: ^0.6.7
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  firebase_storage: ^3.1.6
  flutter_spinkit: ^4.1.2+1



dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Avenir-black
      fonts:
        - asset: fonts/avenir-black.ttf
    - family: Avenir-heavy
      fonts:
        - asset: fonts/avenir-heavy.ttf
    - family: Avenir-roman
      fonts:
        - asset: fonts/avenir-roman.ttf
    - family: Avenir-medium
      fonts:
        - asset: fonts/avenir-medium.ttf